CELERY:
  BROKER_URL : "amqp://arl:arlpassword@arl-master:5672/arlv2host"


MONGO:
  URI : 'mongodb://admin:admin@arl-master:27017/'
  DB : 'arl'


#演示帐号有查询额度限制，请前往 https://community.riskiq.com/ 注册自己的key并替换
RISKIQ:
  EMAIL: "n1un1u2019@qq.com"
  KEY: "03da3c29cce5152a536bae332f7b03a288154b37a13b93921225d3ade49c9b4c"

#GeoIP 数据库文件配置项
GEOIP:
  CITY: '/data/GeoLite2/GeoLite2-City.mmdb'
  ASN: '/data/GeoLite2/GeoLite2-ASN.mmdb'


#Fofa API 配置项
FOFA:
  EMAIL: ""
  KEY: ""


ARL:
  AUTH: true
  #API 认证key, 可以访问api/doc查看文档
  API_KEY: ""
  BLACK_IPS:
    - 127.0.0.0/8
    - 0.0.0.0/8
    - 172.16.0.0/12
    - 100.0.0.0/8
    #- 10.0.0.0/8
    #- 192.168.0.0/16
