CELERY:
  BROKER_URL : "amqp://arl:arlpassword@arl-master:5672/arlv2host"


MONGO:
  URI : 'mongodb://admin:admin@arl-master:27017/'
  DB : 'arl'


#演示帐号有查询额度限制，请前往 https://community.riskiq.com/ 注册自己的key并替换
RISKIQ:
  EMAIL: "n1un1u2019@qq.com"
  KEY: "03da3c29cce5152a536bae332f7b03a288154b37a13b93921225d3ade49c9b4c"

#GeoIP 数据库文件配置项
GEOIP:
  CITY: '/data/GeoLite2/GeoLite2-City.mmdb'
  ASN: '/data/GeoLite2/GeoLite2-ASN.mmdb'


#Fofa API 配置项
FOFA:
  EMAIL: ""
  KEY: ""

#钉钉消息推送配置
#钉钉添加机器人，请查看
#https://github.com/TophantTechnology/ARL/wiki/ARL%202.3%20%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E
DINGDING:
  SECRET: ""
  ACCESS_TOKEN: ""

#邮件推送配置
EMAIL:
  HOST: ""
  PORT: ""
  USERNAME: ""
  PASSWORD: ""
  TO: ""

ARL:
  AUTH: true
  #API 认证key, 可以访问api/doc查看文档
  API_KEY: ""
  BLACK_IPS:
    - 127.0.0.0/8
    - 0.0.0.0/8
    - 172.16.0.0/12
    - 100.0.0.0/8
    #- 10.0.0.0/8
    #- 192.168.0.0/16

  #端口对应前端测试选项
  PORT_TOP_10: "22,25,80,81,88,443,3389,8009,8080,8081,7001,5000,3000,6379,3306,8443,11211"
  #域名爆破字典前端大字典选项
  DOMAIN_DICT: "/code/app/dicts/domain_2w.txt"
  #文件泄漏字典
  FILE_LEAK_DICT: "/code/app/dicts/file_top_2000.txt"