version: '3'

services:
    worker:
        image: tophant/arl:latest
        container_name: arl_worker
        restart: unless-stopped
        volumes:
          - ./arl_worker.log:/code/arl_worker.log
          - ./config-docker.yaml:/code/app/config.yaml
          - ./image:/code/app/tmp_screenshot
        entrypoint: ["sh", "-c", "celery -A app.celerytask.celery worker -l info -Q arltask -c 2 -O fair -f arl_worker.log"]
        environment:
          - LANG=en_US.UTF-8
          - TZ=Asia/Shanghai
